version: '3'
services:
  frontend:
    image: nginx:alpine
    ports: ["8080:80"]
  backend:
    image: mendhak/httpbin:latest
    ports: ["8081:80"]
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: studentpass123
    volumes: ["dbdata:/var/lib/postgresql/data"]
volumes:
  dbdata:
