services:
  frontend:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./frontend-html:/usr/share/nginx/html:ro
  backend:
    image: kong/httpbin
    ports:
      - "8081:80"
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: studentpass123
      POSTGRES_USER: student
      POSTGRES_DB: student_records
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres-data:

