version: '3'
services:
  frontend:
    image: nginx:alpine
    ports: ["8080:80"]
    # Ensure local changes to index.html can be tested
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
  backend:
    image: kong/httpbin
    ports: ["8081:80"]
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: studentpass123
    volumes: ["dbdata:/var/lib/postgresql/data"]
volumes:
  dbdata:
